### ISSUE TITLE
convert.py requires json2html installed on Mac OS 

### ISSUE THREAD

**Issue by henrywangpuppet** [puppetlabs/support-script-analyzer#2]
When I first run this command convert.py:

```
support-tooling git:(master) ./support_parse.sh modules ~/Downloads/puppet_enterprise_support_42544_int-puppetmaster-02_20201229131528.tar.gz | ./convert.py
Traceback (most recent call last):
  File "./convert.py", line 3, in <module>
    from json2html import *
ImportError: No module named json2html
couldn't create json
```
sudo pip install json2html can resolve the issue, this should be mentioned as a requirement.

Plus the above command will throw an error anyway. We need to output to a file then feed it into `convert.py` which is as documented.

**Comment by m0dular** [comment]
Fixed in #11.  The requirement to dump the json output to a file is mentioned in the README.
