### ISSUE TITLE
General Feedbacks 1

### ISSUE THREAD

**Issue by henrywangpuppet** [puppetlabs/support-script-analyzer#4]
the `tech_check` job is very cool, we can immediately find OOM now 👍  

Some other feelings:

(1) Infrastructure states: this is helpful and straightforward. I can see `tech_check` generating it for support script from PE 2019.2.2 but bypass it for another support script from PE 2018.1.8. Any reason for this? There is a `puppet_infra_status.json` in the testing PE 2018.1.8 script bundle with all the information so technically we may get it into our `tech_check`.

There are also some other differences compared to the 2 support scripts like missing `Modules` but I think that is less important. 

(2) The log error part. Are we currently only analyzing the `puppetserver` service log or all `puppet services logs`? If we will analyze other logs as well, thinking it should be better we separate them into different keys.

**Comment by coreymbe** [comment]
Going to piggyback here to provide more general feedback; would be nice to be able to see 500 errors from access logs.

**Comment by jarretlavallee** [comment]
@henrywangpuppet What things would you like to see from the other services in question 2?

@coreymbe All 500 errors from the access logs, or something specific? Do you also want to see 404s, 503, etc?

**Comment by coreymbe** [comment]
@jarretlavallee :: That particular scenario I was looking for `503` errors from `puppetserver_access.log`. But yes, I would want to see 404's, 503's and the like, even if that was output from a separate task.

**Comment by henrywangpuppet** [comment]
@jarretlavallee actually, my second question is to ask if we only have `puppetserver` log or we already analyze others. If we will analyze others, we should separate them clearly in different sessions. 

To your question, I think maybe PuppetDB and/or (PostgreSQL) Error is good to have?

**Comment by jarretlavallee** [comment]
Sounds good @coreymbe and @henrywangpuppet. The goal is to understand what will make this more valuable and useful. There look to be some bugs in it, which we can fix. The main objective is to identify features and bugs so we can prioritize the work. 

Based on the feedback in this I have opened #9 and #10. I am closing this out for specific issues. Please open new feature requests as you have them and feel free to add to the ones I just opened.
