### ISSUE TITLE
Add error logs for all PE components

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/support-script-analyzer#9]
## Use Case
Currently, only the puppetserver error logs are shown in the output. PE has several components and should show the errors from all of the PE services.

## Describe the Solution You Would Like
Add the same functionality as the puppetserver error logging output for the following services.

* PuppetDB
* Orchestrator
* Console Services
* PostgreSQL
* Ace sever
* Bolt server
* nginx

**Comment by m0dular** [comment]
Looking into this, it does parse all logfiles ending in `log`.  For example, I have a sup script with many of these errors in `puppetdb.log`

```
2021-03-03T00:00:01.845-05:00 ERROR [p.t.s.s.status-core] Status check for puppetdb-status threw an exception
```

The errors show up in the output.

```
"181: Status check for puppetdb-status threw an exception",
```

I also think we should use `pgbadger` for everything postgres since it does such a good job.

**Comment by m0dular** [comment]
@jarretlavallee Any thoughts or suggestions on this issue?

**Comment by jarretlavallee** [comment]
@henrywangpuppet ^^

**Comment by m0dular** [comment]
Closing since I think this was opened in error.
